### ISSUE TITLE
Dynamically generate IDs of Widget

### ISSUE THREAD

**Issue by MangelMaxime** [Herebris/Hink#1]
For the moment, the solution used is `int __LINE__` which generate an int from the line number in the file.

But this won't support widgets generate in loops etc.

I think that we should create a Fable plugin to generate Unique IDs. Can't simply used GUID because, we need to have a Fixed ID for one given Widget.

**Comment by alfonsogarciacaro** [comment]
Where are the __LINE__ macros? I couldn't find them 😕 

Also, what are the IDs needed for? If I understand it correctly, there should be one static ID per Widget type, right? Can't you use just the type reference or similar?

**Comment by MangelMaxime** [comment]
I have been added the **LINE** macros in the develop branch. See [here](https://github.com/Herebris/Hink/blob/develop/Source/App.fs#L22).

Each widgets or at least each widget that we want interactive like the *Button* or *Slider* need to have an IDs. 
Displaying widget which have only one simply state like the *Label* don't need it.

IDs are used to identify the `hotItem` and the `activeItem` [definied here](https://github.com/Herebris/Hink/blob/develop/Source/GUI.fs#L15-L16).

`hotiem` is used to stored the ID of the currently hovered widget if there is one hovered.
`activeitem` is used to detect if the widget currently `hot` is interacted with.

Explanation for the button:
Let's say we only have 1 button in the app. Button's ID is 1.

If the mouse is not over the button then current State is:

```fsharp
{
    HotItem = -1
    ActiveItem = -1
}
```

If the mouse is hover the button (but not clicking). State is:

```fsharp
{
    HotItem = 1
    ActiveItem = -1
}
```

If the mouse is hover the button and down. State is:

```fsharp
{
    HotItem = 1
    ActiveItem = 1
}
```

This example identify how we need to render the Button of ID 1. And also send a result to true if the button has been clicked.

Has every choice is made from the ID value each widgets' ID need to be unique otherwise they will share the same state.

Currently possibly way:

.1. User handle the IDs himself.

It's painful and a lot of errors can occurred
  * During the refactoring
  * Widget create over a loop generation
  * etc.

.2. Use **LINE** macro

It's automatic so this is nice. But you need to make sure to have only one widget per line. And so Widget created over loops is going to fail because they are all on the same line.

Both solution have they problem first is hard to maintain and second is a little less elegant in coding style because I said IDs are int for the moment **LINE** macro return a string. I could switch to a string but comparison could slow down on really big programs.

So we need to find another way to handle the IDs or get rid of them but this will be hard are they are used to maintain the GUI code simply. Thanks to this idea and the GUI `hotitem` and `activeitem` the widgets don't have to retain any information about the GUI or they own state. Everything is common and stored in one place.

I just got an idea to make a working deterministic ID generator on Runtime. I will try to make a first draft of it.

**Comment by MangelMaxime** [comment]
Ok so finally I created an ID generator to resolve the IDs on the runtime. Sill not covering every case but still better than the manual way.

IDs are now string. Yes I said int are better for comparison but for know let's use string because they allow us more flexibility.

ID_Generator have an instance method `Gen`

```fsharp
  type ID_Generator = 
    { Counters: Dictionary<string, int>
    }

    static member Initial =
      { Counters = new Dictionary<_,_>()
      }

    member self.Gen (sKey) =
      let out = -1

      match self.Counters.TryGetValue(sKey) with
      | true, x -> 
        self.Counters.[sKey] <- x + 1
        concatKeyValue sKey (x + 1)
      | _ -> 
        self.Counters.Add(sKey, 1)
        concatKeyValue sKey 1
```

This method will try to find a match for the given clean in the internal Dictionary.

If we find a match then we update the counter for this key and return an ID of the format: [key]+[counterValue].

If we don't find a match then we initialize the counter for the keys and return an ID of the format [key]+1.

```fsharp
// ID_Generator has 3 steps for now.
// Step1. Instance a instance of ID_Generator
let ID = ID_Generator.Initial

// Step 2. Reset the ID_Generator at the beginning OR the end of each of you rendering loop
// In the next sample I Reset before the draw
  let rec render _ =
    ID.Reset() // Reset the generator
    GUI.Prepare () // Prepare the GUI to a new draw

    // Build you GUI here
    // Step 3. Generate an ID every time you need one
    if GUI.Button(ID.Gen(__LINE__), "Click me", 50., 50.) then
      clickCount <- clickCount + 1
    
    GUI.Slider(ID.Gen(__LINE__), 50., 150., 20., sliderValue)
    |> ignore
```

This generator + the **LINE** macro solve the problem of maintaining the ID manually and of the widget generated over a loop. Because each time an ID is requested for a certain Key, we suffix it we a unique counter value of the current draw call.

If we have several widgets draw on the same line we could still encounter some rough edge but I would not encourage do that because the code could become messy.

I will do some more test during the next and probably clause this issue for the moment if not more special cases are encounter. This should be enough for a first time.

**Comment by alfonsogarciacaro** [comment]
I still don't understand exactly why you can't use GUID (Fable supports `Guid.NewGuid()`). Thought it's true you'll get different GUIDs if you create one for every `render` iteration (and may not be very performant either).

**Comment by MangelMaxime** [comment]
## RMGUI vs IMGUI

I am not writing a GUI using *Retained Mode* which will store a lot of information about the GUI, Widget, etc. A RMGUI will generate a Widget only once with an ID, and allow the user to modify the Data stored in the Widgets.

An *Immediate Mode* GUI don't store any information about a widget. For example, in Hink if you do
`GUI.Button(ID.Gen(__LINE__), "Click me", 50., 50.)` this will "create" a button each time. And it's up to you to store the "Click me" value.

## Hink case (IMGUI)

### Definitions

- **Hot**: Mean widget was under the mouse
- **Active**: Mean widget was interacting with the Mouse (button left pressed for example)

### Hink implementation

1. A button store nothing about is state over the time because it's don't really exist in memory it's just a function call.
2. GUI maintain an internal state between each rendering loop. Mouse state (position, button clicked, etc.) and Widget's ID of which was hot or active. Because we need those minimal information to know if a click occurred for example. 

#### Sample: How to detect a button click

Code:

```fsharp
(not self.Mouse.Left) && self.HotItem = id && self.ActiveItem = id
```

1. Mouse left button should not be down
2. Button ID should be the one hot
3. Button ID should be the one active

### Requirements/Limitation of Hink

We need to make sure that Button is having the same ID each time we render the GUI. Otherwise, the ID stored in GUI state will not match the new one.

I have to admit this is a bit tricky to understand. And could become a limitation.
For the moment, I don't have another idea in mind other than the one made with `ID_Generator` type.
Because over the runtime, the macro **LINE** will always have the same value has it's a constant on compilation :)

**Comment by alfonsogarciacaro** [comment]
Ah, ok. I didn't know about Immediate Mode GUIs. Thanks a lot for the explanation! I understand the problem much better now :+1:

The simplest solution I can think at the moment is to force the developer to pass a label to GUI constructors. I know this is just passing the responsibility to the user, but maybe it's not much more difficult than calling the `ID_Generator` and should prevent unexpected conflicts (if the developer doesn't pass duplicated labels, of course).

**Comment by MangelMaxime** [comment]
The good thing is that me I prefer to user `ID_Generator` because I understand how it's work and also the limitation (which will need documentation etc.). But as an ID is just a `string`the user can simply pass whatever value he wants :).

For example, if for him it's make more sense to have the ID `"click_me"` he can pass it.

**Comment by MangelMaxime** [comment]
Finally, I think this is possible to remove the need of HotItem and ActiveItem need.
If we can then, the user don't have to handle the IDs.

We will however still need IDs for groups like Layout, RadioButton, TreeView because they need more information than just their own.
For example, an horizontal Layout need to now the number of widget inside of it to manage the auto layout system.

**Comment by MangelMaxime** [comment]
I am rewriting Hink so i should not need ID to identify the elements now.

The new rework should be a mixed between IMGUI and RMGUI.
